[package]
name = "pulldown-cmark"
version = "0.0.8"
authors = [ "Raph Levien <raph@google.com>" ]
license = "MIT"
description = "A pull parser for CommonMark"
repository = "https://github.com/google/pulldown-cmark"
keywords = ["markdown", "commonmark"]

build = "build.rs"

[[bin]]
name = "pulldown-cmark"
doc = false

[dependencies]
bitflags = "0.7"
getopts = "0.2"

[dev-dependencies]
html5ever = "0.20"
lazy_static = "0.2"
regex = "0.2"
tendril = "0.4"

[features]
default = []
gen-tests = []
