[package]
name = "pulldown-cmark"
version = "0.0.3"
authors = [ "Raph Levien <raph@google.com>" ]
license = "MIT"
description = "A pull parser for CommonMark"
repository = "https://github.com/google/pulldown-cmark"

[dependencies]
getopts = "*"
bitflags = "0.3"
