[package]
name = "pulldown-cmark"
version = "0.0.8"
authors = [ "Raph Levien <raph@google.com>" ]
license = "MIT"
description = "A pull parser for CommonMark"
repository = "https://github.com/google/pulldown-cmark"
keywords = ["markdown", "commonmark"]

build = "build.rs"

[[bin]]
name = "pulldown-cmark"
doc = false

[dependencies]
getopts = "0.2"
bitflags = "0.7"

[features]
default = []
gen-tests = []
